name: FlanPlugin
version: 1.0.0
main: FlanPlugin
api-version: 1.18
commands:
  sbf:
    description: All commands related to Snowball Fight
  parkour:
    description: All commands related to the Parkour
  twd:
    description: All commands related to The Walking Datalog
  spawn:
    description: Teleports to spawn