name: FlanSnowballFight
version: 1.0.0
main: SnowballFight
api-version: 1.18
commands:
  sbf:
    description: SnowballFight main commands
  parkour:
    description: All commands related to the parkour